### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by zacekjakub** [jons/minecraft-chunk-deleter#1]
Hi, tried like this and I am getting: no main manifest attribute, in MCChunkDeleter-1.0.5.jar

java -jar MCChunkDeleter-1.0.5.jar --worldFolder=world/ --defragment

Do you know what is the problem, please? Thank you! :)

**Comment by jons** [comment]
i did not provide for a compilation path for use with `-jar` but you can use `-cp` as indicated in `example.sh` (or feel free to change the build/package procedure)

here also is the invocation i last used on my own server, similar to `example.sh` from the repository:

```
java -cp .:MCChunkDeleter-1.0.5.jar nl.joranderaaff.minecraft.chunkdeleter.Main \
  --border=0 \
  --minY=120 \
  --maxY=127 \
  --radius=256 \
  --blockIDs="10,11" \
  --worldFolder=test1
```

**Comment by zacekjakub** [comment]
Thanks, it's working now. :) I was just a bit surprised it didn't compress my world with --defragment glag, I thought it's going to be smaller. :)
 But nevermind and thank you!

**Comment by jons** [comment]
possibly someday i will give the defragmentation code some treatment. really the whole thing need to be rewritten, but i only adopted it because it was abandoned and just to fix one little thing. best of luck!
